<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.Blazor" Version="4.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imbas.Core\Imbas.Core.csproj" />
    <ProjectReference Include="..\Imbas.UI\Imbas.UI.csproj" />
  </ItemGroup>

</Project>
